services:
  boda-valen-benja:
    build: .
    container_name: boda-valen-benja
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/dev.db
      - JWT_SECRET=valentina-benjamin-boda-secret-key-2026
    volumes:
      - ./data:/app/data
      - ./uploads:/app/public/uploads
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
